# Generated by Django 5.0.1 on 2024-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField()),
                ('element', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('atomic_mass', models.DecimalField(decimal_places=5, max_digits=10)),
                ('number_of_neutrons', models.IntegerField()),
                ('number_of_protons', models.IntegerField()),
                ('number_of_electrons', models.IntegerField()),
                ('period', models.IntegerField()),
                ('group', models.IntegerField()),
                ('phase', models.CharField(max_length=20)),
                ('radioactive', models.BooleanField()),
                ('natural', models.BooleanField()),
                ('metal', models.BooleanField()),
                ('nonmetal', models.BooleanField()),
                ('metalloid', models.BooleanField()),
                ('types', models.CharField(max_length=20)),
                ('atomic_radius', models.DecimalField(decimal_places=2, max_digits=6)),
                ('electronegativity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('first_ionization', models.DecimalField(decimal_places=2, max_digits=6)),
                ('density', models.DecimalField(decimal_places=2, max_digits=8)),
                ('melting_point', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boiling_point', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number_of_isotopes', models.IntegerField()),
                ('discoverer', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('specific_heat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_shells', models.IntegerField()),
                ('number_of_valence', models.IntegerField()),
            ],
        ),
    ]
